version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker version
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
          $HOME/miniconda/bin/conda create -n py36 python=3.6 anaconda
          $HOME/miniconda/bin/conda activate py36
          conda install -c bioconda cwltool
          ls
