version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker version
          apt-get install -y python3 python3-pip
          virtualenv -p python3 venv
          source venv/bin/activate
          pip install cwlref-runner
          pip install cwltool
          ls
          
